### ISSUE TITLE
If using root_endpoint, some links are broken

### ISSUE THREAD

**Issue by tkoeberl** [guilhemmarchand/trackme#106]
thanks for the great app. We have a little issue. We are using:
web.conf:
```[settings]
root_endpoint = /splunksubURL
```
splunk is reachable via: https://<host>:8000/splunksubURL  
But some links are not working. E.g. the link to the search in the "Actions for data source" overlay.  
Any ideas for a quickfix?

**Comment by guilhemmarchand** [comment]
Hi @tkoeberl 

Sorry for the delay in response, I missed the notification.

Oh right I see, I will need to verify, the URL is built automatically in Javascript underneath, not sure what the impact is when changing the root_endpoint.

I will check and let you know if any quick fix you can apply.

Guilhem

**Comment by guilhemmarchand** [comment]
@tkoeberl 

I couldn't reproduce your issue, while I am using a cutom value in web.conf | root_endpoint, the search link brings me to the proper URL version:

![image](https://user-images.githubusercontent.com/7503059/87250167-131da780-c45b-11ea-8dfe-9c2eb989872c.png)

Can you tell me more about the URL path that the app generates on your side ?

Could double check on different Web Browsers too please ?

Thanks

**Comment by guilhemmarchand** [comment]
@tkoeberl 

Actually I think it can be easily avoided, by replacing the attempt to build the proper full URL by using a relative path approach.

If you have a testing env this is included in version 1.2.18:

https://github.com/guilhemmarchand/trackme/tree/version_1218

**Comment by tkoeberl** [comment]
@guilhemmarchand 
Yes the version .18 works as expected. But remembered now we had that in the past with the aws app. Will talk to the loadbalancer guys why that happens.
thanks a lot for the great app and the brilliant support.

**Comment by guilhemmarchand** [comment]
You are very welcome @tkoeberl 
Thanks

**Comment by tkoeberl** [comment]
Sorry for reopening.. Still having the issue in some cases. e.g. Manage "allowlists&blocklists"->"manage blocklist sourcetypes" -> check one sourcetype and try to delete it. In the following dialog the Delete button is not working.
I commented in the debug messages and got this in the console:
![image](https://user-images.githubusercontent.com/16901385/88647884-c37be480-d0c6-11ea-9d14-8b1182904b60.png)

**Comment by guilhemmarchand** [comment]
Hi @tkoeberl 

Copy that, I will verify this.
This is a communication that should happen locally between Splunk Web process and Splunkd REST API so I will double check.

**Comment by guilhemmarchand** [comment]
One question @tkoeberl 

Does it always fail when you try to remove an entry ? 
There is a small weakness in the variable management right now with the new check box in table thing which makes that when you delete an entry, then you select a new entry, the previous that was deleted is still part of the array.

When the javascript is then going trhough the array of keys, it verifies if the key exists before trying to remove it, therefore the check will generate a 404 in the console logs.

**Comment by tkoeberl** [comment]
Hi @guilhemmarchand ,
it always happens,the only 404 can you see in the screenshot. My testcase was: create an entry, refresh lookup, delete the entry.

**Comment by guilhemmarchand** [comment]
Thanks @tkoeberl 
So I understand even in the main tab like data sources tracking you cannot delete an entry (correct me otherwise)
To say it differently it happens in all screens that allow deleting a record 

Seems like proper to your environment but I am doing verifications

**Comment by guilhemmarchand** [comment]
The following search might in between be showing up interessting facts:
`index="_internal" sourcetype=splunkd_ui_access "*trackme*" status!=200 status!=201`

**Comment by tkoeberl** [comment]
> So I understand even in the main tab like data sources tracking you cannot delete an entry (correct me otherwise)
> To say it differently it happens in all screens that allow deleting a record

If I use Delete->Delete temporary -> Ok I get a nice exception:
![image](https://user-images.githubusercontent.com/16901385/88806767-20ec6000-d1b1-11ea-9e8d-894df13ec7eb.png)

**Comment by guilhemmarchand** [comment]
Hi @tkoeberl 

Did you have any progress on your issues ?
I haven't been able to reproduce any of your issues while using a custom root_endpoint in Splunk Web.

Guilhem

**Comment by tkoeberl** [comment]
Hi @guilhemmarchand 

no progress. tried with the LB guys. They dont have any idea whats goign wrong. Could it be about a lost header in the transmission? Or is the browser trying to reach 8089 directly?

thanks,
-thomas

**Comment by guilhemmarchand** [comment]
Right @tkoeberl thanks 

Actually, these interactions like updating a record in a KVstore are performed internally between the Splunk Web processes which act as the front-end to splunkd rest API.
It is not really the browser trying to access to splunkd, the browser talks to Splunk Web which itself talks to splunkd.

I guess some headers transformations could be in cause indeed but the question remains opened.

We certainly could have a test in a simplified UI, I will design one and let you know

**Comment by tkoeberl** [comment]
Just tried again via the LB. 
On using the delete button, there is no entry in splunkd_access.log, but I've found a difference between the calls with LB or without:  
This one return 200:  
https://<servername>:8000/en-US/splunkd/__raw/servicesNS/nobody/trackme/storage/collections/data/kv_trackme_custom_lagging_definition/5f2bca0cd6b5ddd2cd219951?_=1596705783535

this one returns 404:
https://<LBUrl>/en-US/splunkd/__raw/servicesNS/nobody/trackme/storage/collections/data/kv_trackme_custom_lagging_definition/5f2bca0cd6b5ddd2cd219951?_=1596705497999

If I now add the /splunk/ part for the call, I get a 200
https://<LBUrl>/splunk/en-US/splunkd/__raw/servicesNS/nobody/trackme/storage/collections/data/kv_trackme_custom_lagging_definition/5f2bcf35d6b5dd0939609c61?_=1596706350573

To be honest I wonder now why the direct call works wihtout the "/splunk/" part,

**Comment by guilhemmarchand** [comment]
if you pick up one KVstore entry:

| inputlookup trackme_data_source_monitoring | eval keyid=_key
| head 1
| fields keyid

the key is the unique ID of the record in the KV, for example in your Web Browser you should be able to reach its content like:

https://my.splunkinstance.com/en-US/splunkd/__raw/servicesNS/nobody/trackme/storage/collections/data/kv_trackme_data_source_monitoring/01ac6d657f293125186aad33c1515296

**Comment by guilhemmarchand** [comment]
If I run a Splunk instance locally with a custom root, I get for example:

https://localhost:8000/splunktest/en-US/splunkd/__raw/servicesNS/nobody/trackme/storage/collections/data/kv_trackme_data_source_monitoring/07025724a9df0a3efde4296ca742abcb

When the app does it, it uses something like:

```
            // Create the endpoint URL
            var myendpoint_URl = "/en-US/splunkd/__raw/servicesNS/nobody/trackme/storage/collections/data/kv_trackme_data_source_monitoring/" + tk_keyid;

```

And the start of the URI should be relative and not affected by the custom root, in my tests it isn't it

**Comment by tkoeberl** [comment]
Just came something in my mind, which I always forget.. the proxy server shoudl be involved in the LB case as well. Need to play around with some settings.

**Comment by tkoeberl** [comment]
Hi @guilhemmarchand,
maybe I found something.. 
I enabled your debug in: 
TrackMe.html in line 19809
`console.log("foreachDeleteLaggingClassDataSource - Endpoint URL is: " + myendpoint_URl);`

This gives me in the browser: (no matter of proxy/loadbalancer/direct)
`foreachDeleteLaggingClassDataSource - Endpoint URL is: /en-US/splunkd/__raw/servicesNS/nobody/trackme/storage/collections/data/kv_trackme_custom_lagging_definition/5f2be7df0a14ef53476769f2`

Should'nt that not be:
`foreachDeleteLaggingClassDataSource - Endpoint URL is: /splunk/en-US/splunkd/__raw/servicesNS/nobody/trackme/storage/collections/data/kv_trackme_custom_lagging_definition/5f2be7df0a14ef53476769f2`

I think the line is wrong.
`var myendpoint_URl = "/en-US/splunkd/__raw/servicesNS/nobody/trackme/storage/collections/data/kv_trackme_custom_lagging_definition/" + item;
`
With that line you completely ignore the localization, right?

If you try to debug that on your local instance you would see it working, cause splunk is listening to "/splunk/" and "/". But it should not listen on "/" 

If I change the line to:
`var myendpoint_URl = "/splunk/en-US/splunkd/__raw/servicesNS/nobody/trackme/storage/collections/data/kv_trackme_custom_lagging_definition/" + item;
`
it works as it should.

**Comment by guilhemmarchand** [comment]
Thanks @tkoeberl  this is very useful indeed, great progress in understanding the issue now.

"/splunk/en-US/splunkd" is only valid in your context, so I need to find the way to detect the root context and apply it to the REST calls when it differs from / 

I am currently working on a very exciting new feature for TrackMe but I will look into it shortly

**Comment by guilhemmarchand** [comment]
Using the following builtin variable will do it:

`{{SPLUNKWEB_URL_PREFIX}}`

For example in a lab instance with a custom root url it would be:

/splunktest/en-GB

So the URI like for instance:

`var myendpoint_URl = "{{SPLUNKWEB_URL_PREFIX}}/splunkd/__raw/servicesNS/nobody/trackme/storage/collections/data/kv_trackme_data_source_monitoring/" + tk_keyid;`

Works as expected in all contexts.

I will work this out for a fix release for you shortly and referencing this isssue. (version 1.0.21)

**Comment by guilhemmarchand** [comment]
@tkoeberl 

if you have a testing environment, or you can test the new version of "trackme/default/data/ui/html/TrackMe.html" this should fix all the issues related to the context.

Please let me know, thanks!

Guilhem

**Comment by tkoeberl** [comment]
@guilhemmarchand :
great! looks like it did the trick 👯

**Comment by guilhemmarchand** [comment]
Perfect @tkoeberl ;-)
I will publish the release shortly.

Thank you very much for your help making TrackMe even better!

Guilhem
