### ISSUE TITLE
monitoring of host:source combination should be possible

### ISSUE THREAD

**Issue by tkoeberl** [guilhemmarchand/trackme#107]
Would it be possible to habe a host:source combination monitoring?

**Comment by guilhemmarchand** [comment]
Hi @tkoeberl 

**This is the purpose of the Elastic source concept:**

https://trackme.readthedocs.io/en/latest/userguide.html#elastic-sources-creation-and-usage

Whenever there are use cases that the default concept would not comply with, you can add your custom sources in as part of the shared Elastic Sources, or as a dedicated tracker.

A source from the Splunk Meta point of view is traditionally a the path to the file, in cases I understand this can be defined based on a naming convention that fits the use case like ingestion from tcp inputs, HEC, Kafka etc 

But the Elastic Sources allows to cover all the use cases at glance with any of our language available.

Guilhem

**Comment by tkoeberl** [comment]
okay, will try that. Wanted to make sure that it's not on the roadmap.

**Comment by guilhemmarchand** [comment]
No problem @tkoeberl 

Nope it's not and it would not be wanted (and we have the Elastic source for that) because it would fit some use cases but not the majority of them.

Guilhem
