### ISSUE TITLE
add comment to acknowlegde alert

### ISSUE THREAD

**Issue by tkoeberl** [guilhemmarchand/trackme#124]
@guilhemmarchand 

It woudl be really helpful to have the comment of the latest acknowdgement in the dialog.

This dialog:
![image](https://user-images.githubusercontent.com/16901385/90405453-0a487300-e0a4-11ea-9892-7cd0afaabd99.png)

serach is something like:
```
| `trackme_ack_get("0200-ops_network_dispatcher-dnsdhcp:ib:dns:captures", "data_source")` 
| join object 
    [| inputlookup trackme_audit_changes
    | sort - time
    | head 1
    | fields comment, object
    ]
    | fields object, object_category, ack_mtime, ack_expiration, ack_state, comment
```

**Comment by guilhemmarchand** [comment]
Thanks @tkoeberl 

Included in Version 1.2.21 in the testing branch currently.
