### ISSUE TITLE
Possible Bug in Data Sources Modify section

### ISSUE THREAD

**Issue by cidermark** [guilhemmarchand/trackme#131]
Hi, 

I think I may have found a small bug when modifying the max lag time for a data_name. Under a certain situation ( this may also happen in other scenario’s too???) the ‘Alert overKPIs’ value become ‘null’.

I noticed this in the following scenario:
Monitoring is disabled
Change the max lag time from 3600 to 86400
Apply Manual Logging Rule
back
Enable monitoring
Open the Modal window again and click modify
The  ‘Alert overKPIs’  value is now ‘null’

Cheers,
Mark.

**Comment by guilhemmarchand** [comment]
Thanks for reporting @cidermark 
Will be investigated shortly!

Kind regards,
Guilhem

**Comment by guilhemmarchand** [comment]
Issue located, thanks!

Line 19909:

`var tk_data_lag_alert_kpis = tokens.get("tkdata_lag_alert_kpis");`

Should be:

`var tk_data_lag_alert_kpis = tokens.get("tkdata_lag_alert_kpis");`

Will be fixed in upcoming 1.2.22 ;-)

Kind regards,

Guilhem
