### ISSUE TITLE
Enhancement - ability to search for hosts in Data Hosts Tracking by Logical Group Name

### ISSUE THREAD

**Issue by alvincruz29** [guilhemmarchand/trackme#141]
Requesting for functionality to allow users to search for all hosts by Logical Group Name.  The search should allow for partial word search.  For example, if there is a logical group named "London Backstage Pass", searching for "Backstage" or "backstage" should display all logical group names with the word "backstage".

**Comment by guilhemmarchand** [comment]
Notes: Will be part of Version 1.2.24

**Comment by guilhemmarchand** [comment]
Version 1.2.24 is now live.
