### ISSUE TITLE
Outlier Config Loses 'OutlierMinEventCount:' Overnight

### ISSUE THREAD

**Issue by cidermark** [guilhemmarchand/trackme#147]
Hi, I've set up Outlier detection for one of our Data Sources but, I think, the 'TrackMe - Volume -30d Outliers update tracker' is resetting it as the values change everyday at approximately 04:00.
My settings are:
OutlierMinEventCount mode: Static
OutlierMinEventCount: 150000

Occasionally the OutlierMinEventCount: just gets reset to null but on other occasions it resets OutlierMinEventCount mode: to Dynamic and OutlierMinEventCount: to 'disabled'

Please feel free to contact me if there's any other info you require.

**Comment by guilhemmarchand** [comment]
Hi @cidermark 

Thank you for reporting, I will check this out and will revert if I have any question.

Guilhem

**Comment by guilhemmarchand** [comment]
@cidermark 

I have not been able yet to reproduce the issue, first question can you confirm which version of the app is current deployed?

Second question, could we make the following verification please:

- Make sure the configuration is applied as you which, example I applied a 10K static lowerbound for that one:

![image](https://user-images.githubusercontent.com/7503059/94000795-929af180-fd8f-11ea-9546-456810f5333c.png)

Then, please run manually the Outliers scheduled report, these are the reports named "TrackMe - Volume * Outliers update tracker

Once they ran, please run manually the short term then the long term trackers.

Finally, checkout the value in the collection after these execution:

```
| inputlookup trackme_data_source_monitoring | eval keyid=_key
| search data_name="firewall:pan:traffic"
| fields data_name, Outlier*

```

Thank for you in advance

Guilhem

**Comment by cidermark** [comment]
Hi @guilhemmarchand,

I ran the search as requested and this time it didn't seem to change the results  ( TrackMe1.jpg ). However, overnight the alert fired again and when I ran your search again, it still showed no change???

I looked at the 'Outlier Detection Overview' ( TrackMe2.jpg ) and noticed that the lower value for the blue bar in the graph was now at, about 635,000 even though the OutlierMinEventCount in the stats was still at 150,000

I then looked at the 'Outlier Detection configuration' ( TrackMe3.jpg ) and the 'OutlierMinEventCount' box was now null/empty.

Not sure that this is very helpful to you, let me know if there's anything else I can look for.
Mark.

![TrackMe_1](https://user-images.githubusercontent.com/59366045/94115694-00075a80-fe42-11ea-820b-9d4791ebe915.jpg)
![TrackMe_2](https://user-images.githubusercontent.com/59366045/94115718-0695d200-fe42-11ea-93d9-3c31e5e20994.jpg)
![TrackMe_3](https://user-images.githubusercontent.com/59366045/94115731-0b5a8600-fe42-11ea-8be4-65b02225715e.jpg)

**Comment by guilhemmarchand** [comment]
@cidermark 

Thank you, I think I get the point.

**Basically, what matters for the workflow is that once you defined a static threadhold for the lower bound, this remains defined as static with the correct value for the OutlierMinEventCount field in the lookup.**

But I am reviewing it carefully.

What is the version of TrackMe deployed please ?

Guilhem

**Comment by cidermark** [comment]
We're currently on v1.2.20. I haven't been able to upgrade to 1.2.22 due to change freeze here :(

**Comment by guilhemmarchand** [comment]
@cidermark 
Version 1.2.24 is now live.
