### ISSUE TITLE
Enhancement: Allow 'NOT' filter for Keyword filter name:

### ISSUE THREAD

**Issue by cidermark** [guilhemmarchand/trackme#148]
Hi,

Would it be possible to have a 'NOT' switch for the Keyword filter in the Tracker pages? We have a large number of similar named data names (over 2000) and I would like to be able to 'hide' those from the list. The only way that I have been able to do this so far is to blacklist / un-blacklist them.

Cheers.

**Comment by guilhemmarchand** [comment]
Note: Will be part of 1.2.24

**Comment by guilhemmarchand** [comment]
@cidermark 
Version 1.2.24 is now live.
