### ISSUE TITLE
Enhancement - UI to allow users to delete metric_category entries in Metrics Host Tracking table 

### ISSUE THREAD

**Issue by alvincruz29** [guilhemmarchand/trackme#166]
There are times when users need to clean up the data sources attached and displayed as entries in the metric_details_human column on the Metric Host Tracking page.  For example, 1 data source (metric type) was initially configured to go through an intermediate heavy forwarder.  Then, changes are made to have this same data source events go through a different intermediate forwarder or load balancer.  Currently, the metric category for the data source remains "attached" to the original intermediate forwarder and since the data is no longer detected there, that metric category goes in red state which also makes the entire metric host go red.  

Enhancement Request:  We need an easy UI for users to remove metric_category entries from metric_hosts.

<img width="1614" alt="metric_category_entries" src="https://user-images.githubusercontent.com/29575634/95484346-36b29a00-0945-11eb-952d-6bdf7ff261d3.png">

**Comment by guilhemmarchand** [comment]
@alvincruz29 

This will be available in Version 1.2.24 with a reset button made available for the UI to perform a reset of the metrics known for that given host.

![image](https://user-images.githubusercontent.com/7503059/95619305-51c8fb00-0a66-11eb-880b-f157e662e559.png)

**Comment by guilhemmarchand** [comment]
Version 1.2.24 is now live.
