### ISSUE TITLE
Issue - Pressing "Manage: manual tags" displays dialog with ALL tags in "List of current tags for this data source" field

### ISSUE THREAD

**Issue by alvincruz29** [guilhemmarchand/trackme#167]
Steps to reproduce: 

1. Add multiple tags to 1 data source in Data Sources Tracking
2. Select a different data source --> Click here to define tags link or Show Tags 
3. Click on "Manage: manual tags" button
4. The "List of current tags for this data source, unselect a tag to remove it and click on the save button:" field contains all tags that have been created including the ones created in step 1.  This is misleading because the displayed tags do not belong to the current data source being modified.
5. Even though all the tags that have been created are displayed in the field, adding a new tag does not add the others to the current data source being modified.  This is good and expected.

![image](https://user-images.githubusercontent.com/29575634/95525427-f2e18400-0988-11eb-916d-948f4ffc7cce.png)

**Comment by guilhemmarchand** [comment]
Thanks for reporting @alvincruz29 
Fix in upcoming version 1.2.24

**Comment by guilhemmarchand** [comment]
Version 1.2.24 is now live.
