### ISSUE TITLE
Enhancement - Automatically Backup Main KV Store collections

### ISSUE THREAD

**Issue by alvincruz29** [guilhemmarchand/trackme#222]
Have a new functionality to automatically backup the main kv store collections for Data Sources Tracking, Data Hosts Tracking, and Metrics Hosts Tracking.  We've recently had a situation at a customer where the defined tracking configs in the above collections were mysteriously deleted.  We had to recreate them as best we could.  If there were nightly backups (like the one available in ITSI), they would have been extremely useful.  Thank you!

**Comment by guilhemmarchand** [comment]
Under review
