### ISSUE TITLE
Feature Request - Splunk Infrastructure Monitoring

### ISSUE THREAD

**Issue by cidermark** [guilhemmarchand/trackme#253]
Hi Guilhem,

Just a thought for an enhancement to your, already excellant, app - some kind of monitoring of the Splunk infrastructure would be very useful. Whilst there is some capability in the Monitoring Console, to have Indexers, Searchheads, Heavy Forwarders, etc monitored from a single resource would make it a lot simpler to manage/monitor.

The problem with much of the Splunk infrastructure is that they don't, necessarily, generate events that are indexed outside of the _internal index e.g. clients checking in with the deployment server or throughput metrics for indexers.

Regards,
Mark.

**Comment by guilhemmarchand** [comment]
Hi @cidermark 
Thank you ;-)

Right, TrackMe has always been focussing exclusively on the data itself, thus I appreciate this is a valid use too.

Will look into this

**Comment by cidermark** [comment]
Super-fast! Thanks.

**Comment by guilhemmarchand** [comment]
Thanks @cidermark !
This is upcoming, finishing a few qualification and will be published very soon ;-)
Thanks again for sharing your thoughts!
