### ISSUE TITLE
Customs Alerts based on priorities

### ISSUE THREAD

**Issue by 11gods** [guilhemmarchand/trackme#262]
Hi,

What an amazing app.
Is it possible to generate an alert if the **priority** is **high** and perform a certain action like **open a ticket** and generate another alert if **priority** is **medium** and perform another action such as **send an email**?

I am aware that I can configure when I want to get alerted based on which priority by modifying the macro Trackme_alerts_priority

Thanks

**Comment by guilhemmarchand** [comment]
Thank you, will be reviewed

**Comment by guilhemmarchand** [comment]
@11gods 
Version 1.2.39 is now live in Splunk Base and brings a new screen for alert managements and assisted alerts creation.
