### ISSUE TITLE
Bug/Enhancement - ID cards

### ISSUE THREAD

**Issue by cidermark** [guilhemmarchand/trackme#266]
Hi Guilhem, 

I'm not sure whether this is a bug or an enhancement request. Currently, when an ID card is updated any sources that are associated with the card are lost and have to be re-added. Would it be possible to have an option to maintain the existing associations?

Also, would it be possible to 'wildcard' the object name for the ID card associations? For example, we have hundreds of indexes that begin with 'aws*cloudtrail'. They would all use the same troubleshooting/remediation documentation and creating the associations would be a pain. I did think of setting the Global ID card to this but there is an equal number of 'aws*cloudfront' indexes that have a different troubleshooting/remediation document :(

I know that I've requested a few enhancements recently, please don't think that I'm in any way critical of your excellent app.

Cheers,
Mark.

**Comment by cidermark** [comment]
Oops, I meant to also add ( sorry ) - markdown in the ID card text frame?

**Comment by guilhemmarchand** [comment]
Thank you @cidermark  and don't worry, I am very happy getting your feedback and inputs.
The answer to the first question is no, when a card is updated that should be removing or changing any association, I need to verify then!

In 1.2.35, I introduced new REST API endpoints, which allows handling the cards:

https://trackme.readthedocs.io/en/latest/rest_api_reference.html#identity-cards-endpoints

Just FYI

**Comment by cidermark** [comment]
Ah yes! I'll look in to creating the associations using the API. Thanks

**Comment by guilhemmarchand** [comment]
@cidermark 

- The UI issues which was leading to loose current associations is fixed in 1.2.36
- A new wildcard matching feature addresses your requirements, please review:

https://trackme.readthedocs.io/en/latest/userguide.html#data-identity-wildcard-matching

Fixed in 1.2.36 published in Splunk Base.
