### ISSUE TITLE
Create Lagging Classes based on Logical Groups

### ISSUE THREAD

**Issue by ptigalry** [guilhemmarchand/trackme#272]
Hi,

We use a logical groups a lot and we would like to have an option to create Lagging Classes based on it.

Thanks in advance,

Regards.

**Comment by guilhemmarchand** [comment]
Thank you @ptigalry 
Will be reviewed ASAP ;-)

**Comment by guilhemmarchand** [comment]
@ptigalry 
This to me isn't the purpose of logical groups, this should be handled via lagging classes.
Closing this issue, let me know if you have any further questions.
