### ISSUE TITLE
Massive Update of Data_max_lag_allowed / data_monitoring_wdays

### ISSUE THREAD

**Issue by 11gods** [guilhemmarchand/trackme#289]
Hi,
It would be nice if we can do a massive upload of the data_name using a csv file.

Example, we would like to update the data_max_log_allowed and data_monitoring_wdays fields.

Thanks

**Comment by guilhemmarchand** [comment]
@11gods 
As far as I am concerned, this specific requirements can be better handled in a few lines of SPL and it is hard enough to capture a use case that would valuable for everyone.

Feel free to let me know if you have more requirements on this one and I will review!
