### ISSUE TITLE
TrackMe bug report - Splunk telemetry causes DateParserVerbose Warnings logged

### ISSUE THREAD

**Issue by steffu3123** [guilhemmarchand/trackme#293]
**Description:**
Some TrackMe scheduled reports generate DateParserVerbose Warnings. Cause of these warnings seems to be a missing timestamp in the *_search_telemetry.json files.

**To Reproduce**
1. Install TrackMe and prerequisites
2. wait at least 5 minutes for TrackMe scheduled reports to execute
3. Search index=_internal sourcetype=splunkd error OR warn DateParserVerbose "\*\_trackme\_\*" returns results
4. Search index=_introspection sourcetype="search_telemetry" | where isnull(timestamp) returns results

**Expected behavior**
No DateParserVerbose Warnings are logged

**Splunk version and deployment:**
- Splunk 8.1.2, 8.1.3
- TrackMe 1.2.20, 1.2.38
- occurs on both Splunk single searchhead and searchhead cluster

**Additional context**

Sample search_telemetry.json:
[search_telemetry.json.txt](https://github.com/guilhemmarchand/trackme/files/6206908/search_telemetry.json.txt)

**Comment by guilhemmarchand** [comment]
Thanks @steffu3123 
Interesting, Splunk telemetry, wondering what's causing the timestamp to be missing.
Telemetry is a Splunk internal thing, surely some stuff in TrackMe is linked to this.

Will investigate

**Comment by guilhemmarchand** [comment]
@steffu3123 

This is not clear to me why this happens and I believe this to be a Splunk core bug in the telemetry generation.
In a single JSON file generated, we can see two well formed JSON payloads, one has a timestamp and this other does not.

I do nothtink this to be related with TrackMe at any direct level, thus this can be workaround from a TrackMe only point of view by including the following props source stanza in the app:

```
# search_telemetry
# Splunk generates date time parsing erros with the search telemetry due to a timestamp missing in the second json payload of a same json generated
# This seems to be a Splunk core issue with telemetry and the root cause was not idenfitied
# however, this can be workaround with a source based stanza forcing the a date time config

[source::.../var/run/splunk/search_telemetry/...trackme...telemetry.json]
TRUNCATE = 99999
DATETIME_CONFIG = CURRENT
```

This will be included in next release.

**Comment by steffu3123** [comment]
Thanks @guilhemmarchand 
I've configured the workaround inlocal/props.conf and I haven't seen any DateParserVerbose warnings so far.

**Comment by guilhemmarchand** [comment]
thanks @steffu3123 for confirming, will be part of next release.
