### ISSUE TITLE
Is there any possibility to track data by source and host?

### ISSUE THREAD

**Issue by vavan11** [guilhemmarchand/trackme#31]
I have many hosts that send logs that end up in one index and each of them has three or two sources.
Sometimes data comes from a particular host, but not from all sources for this host.
Is it possible to track a source on a particular host that stopped sending data?

**Comment by guilhemmarchand** [comment]
Hi @vavan11 
I suppose you mean on the data sources monitoring tab right ?

In the design, I didn't include the source as part of the by statement because of the volatility nature of it, in most cases the source value corresponds to the full file path which can be literally anything and has a low value in normal file monitoring inputs.

Therefore, more specific data sources like Kafka would most likely have a specific source value that makes sense and provides value.

I am looking at additional options to answer to your need, can you detail a bit more ?

**Comment by vavan11** [comment]
For me, it would be very useful to show data by host and sourcetype and not aggregate sourcetypes. 
Can such a possibility be added?

**Comment by guilhemmarchand** [comment]
Right @vavan11 

I think I see an option here, I am thinking about the following:

- On per host basis (the data hosts objects and tab), one could edit the active sourcetypes to be monitored, depending on the rule(s) to be defined, the status for that host would switch from good to bad if one of the mandatory sourcetype(s) is not available.

- On active modal Window (when you click), an information would show clearly the reason why the host is red and the list of sourcetype(s) in alert for that host.

So, the feature would provide a way on a per host basis, and/or eventually with a generic rule that can be applied on some criteria, to say which sourcetype(s) you expect and will rule the host status.

Would that make sense ?

**Comment by vavan11** [comment]
@guilhemmarchan
Thanks for looking into this. It makes sense.
I would prefer the first option but you can go ahead with any other solution that might appear to solve this.

I hope you would be able to add this feature to the next release.

**Comment by guilhemmarchand** [comment]
Hi @vavan11 

Yes I am working on it and any change would be delivered on the next release.

The first option you mention is I suppose "useful to show data by host, sourcetype and not aggregate sourcetypes".
I need to find the level of feature that respects the philosophy and the logic of the workflow but I get your point, simply breaking out by host, sourcetype would create 1 entry for each host / sourcetype that is not blacklisted and would break the logic for most of the users.

I will let you know when I have something ready.

Thank for your interest and using the trackeMe app ;-)

**Comment by vavan11** [comment]
@guilhemmarchand!

Thanks! I do appreciate your cooperation!
I am looking forward to the next release!

**Comment by guilhemmarchand** [comment]
closed for inactivity, please re-open this issue shall it be required.

**Comment by guilhemmarchand** [comment]
Hi @vavan11 

It's been a while but never too late ;-)

This is has been finally fully addressed in Version 1.2.2 with the Elastic sources feature:
https://trackme.readthedocs.io/en/latest/userguide.html#elastic-sources-creation-and-usage

Guilhem
