### ISSUE TITLE
Datasource mode that supports standard AND Cribl modes?

### ISSUE THREAD

**Issue by bowesmana** [guilhemmarchand/trackme#342]
It looks like the Cribl mode support is an on/off, where unless the cribl_pipe field is present in the tstats data, it will subsequently ignore all index/sourcetypes where cribl_pipe does not exist.

I understand it might be challenging to add support for a combined mode, where you can turn on Cribl mode to get the extra information from Cribl derived sources, but still use standard index:sourcetype datasources, where there is no cribl_pipe in tsidx.

Do you think this is something that could be done? It's a really neat feature being able to make use of Cribl meta info, but losing other sources when you turn that on is a shame.

**Comment by guilhemmarchand** [comment]
HI @bowesmana 

That is correct, as soon as you enabel the Cribl mode, TrackMe turns natively into a "Cribl" only mode regarding data sources.
Thus, I understand the question and will document it, to achieve your goal you can simply do the following:

- via Splunk Web (or manually) Clone the short term and long data sources trackers:

TrackMe - Data sources abstract root tracker --> say: "TrackMe - Data sources abstract root tracker - non Crib"

TrackMe - Data sources availability short term tracker --> say "TrackMe - Data sources availability short term tracker - non Cribl"

TrackMe - Data sources availability long term tracker --> say "TrackMe - Data sources availability long term tracker - non Cribl"

- Edit the newly created report "TrackMe - Data sources abstract root tracker - non Crib"

- Locate on the first line:

``
by `trackme_data_source_tstats_root_splitby`
``

And replace by:

``
by `trackme_data_source_tstats_root_splitby_regular`
``

- In the same report, locale:

``
where index=* sourcetype=*
``

And after this, add:

``
cribl_pipe!=*
``

(which will exclude anything that's handled by the native trackers)

- Modify the two newly created report:

"TrackMe - Data sources availability short term tracker - non Cribl"

"TrackMe - Data sources availability long term tracker - non Cribl"

Locate the first line:

``
| savedsearch "TrackMe - Data sources abstract root tracker"
``

And replace with:

``
| savedsearch "TrackMe - Data sources abstract root tracker - non Cribl"
``

(or whatever you named it)

- Automatically, non Cribl data sources will be created and visible in TrackMe

- Note that "run trackers" buttion action in the UI will only handle the native trackers not those, thus it is no big deal.

I am working on something different for the next generation of TrackMe which would addressed this too, but this won't be available before a while, and using the above will very easily achieve your goals.

Let me know if this makes sense, and I will later on add these steps into the Cribl mode documentation for people having the same requirements.

Guilhem

**Comment by bowesmana** [comment]
Hi Guilhem, 

Yes that makes perfect sense - I had wondered if that would be sufficient, as there are a couple of other macros, where cribl is mentioned.

trackme_data_source_cribl_mode
trackme_data_sampling_return_live_sample

and the first one looks like it is dependent on cribl_pipe - but I wasn't sure where that was used. I currently had this deployed in a dev environment - I'll look at the changes you suggest and set them up.

BTW, this is a great app!

**Comment by guilhemmarchand** [comment]
Thanks @bowesmana  appreciate your support ;-)

Yes, you will let me know - we can keep this issue opened for now - anything not working as expected you let me know.

There are different checks that can mention Cribl in the app yes, what does this button in the UI do is the following:

``
        // Update the data sources mode
        function update_data_source_mode(value) {

            var query_url = "/en-US/splunkd/__raw/servicesNS/nobody/trackme/configs/conf-macros/trackme_default_data_source_mode"
            var query_url2 = "/en-US/splunkd/__raw/servicesNS/nobody/trackme/configs/conf-macros/trackme_data_source_tstats_root_splitby"
            var value = value;

            if (value == "trackme_data_source_split_mode") {
                change_type = "enable data source split mode";
                root_splitby_value = "trackme_data_source_tstats_root_splitby_regular";
            } else if (value == "trackme_data_source_merged_mode") {
                change_type = "enable data source merged mode";
                root_splitby_value = "trackme_data_source_tstats_root_splitby_regular";
            } else if (value == "trackme_data_source_cribl_mode") {
                change_type = "enable data source cribl mode";
                root_splitby_value = "trackme_data_source_tstats_root_splitby_cribl";
            } else {
                // default if unset
                change_type = "trackme_data_source_split_mode";
                root_splitby_value = "trackme_data_source_tstats_root_splitby_regular";
            }
``

I will double check and reproduce in LAB to make sure that I am not forgetting something, and will let you know here.

**Comment by guilhemmarchand** [comment]
@bowesmana 

I have reviewed the steps and it was almost this ;-) I forgot the intermediate calculation.

Anyway, it's been documented now, so please follow these steps:

https://trackme.readthedocs.io/en/latest/cribl_integration.html#handling-both-cribl-mode-and-regular-mode

Once you can confirm it's all good for you, please confirm in this issue and proceed to its closure if you like ;-)

**Comment by bowesmana** [comment]
Hi Guilhem,

So far it looks good in the lab - if I see any issues, I will come back to you - really appreciate your amazingly quick turnaround.
