### ISSUE TITLE
Macro URL link from manage/configure page gives 404 in Splunk Cloud

### ISSUE THREAD

**Issue by bowesmana** [guilhemmarchand/trackme#347]
Splunk Cloud:
From the TrackMe_manage page, it is possible to drilldown on a macro definition, which should take you to the edit macro page. This link is like this

/manager/trackme/admin/macros/trackme_default_outlier_period?action=edit

and on a standalone Splunk Enterprise (not Cloud) instance, everything works fine. (8.0.2)

In Splunk Cloud (Version 8.2.2105.2) this link results in a 404 horse. If navigating to the macro page to edit the macro manually, the URL is actually

/manager/trackme/data/macros/trackme_default_outlier_period?action=edit

This is a Splunk Cloud search head with ITSI installed, but not sure if that makes a difference or whether it's just Splunk Cloud.

**Comment by guilhemmarchand** [comment]
Hi @bowesmana!

What is the version of TrackMe deployed in Splunk Cloud?
This issue has been addressed in release 1.2.48: https://github.com/guilhemmarchand/trackme/issues/338

If the version if bellow 1.2.48, please address an upgrade request to Cloud, they will process to the latest version vetting and and upgrade.

**Comment by bowesmana** [comment]
It's 1.2.45 - odd installed only 2 days ago - will request it gets upgraded.
