### ISSUE TITLE
Remember choosen site OR Move/add sitenavigation bar to the top

### ISSUE THREAD

**Issue by bl00mberg** [guilhemmarchand/trackme#351]
**Is your feature request related to a problem? Please describe.**

Aloha!

While working on TrackMe configurations for a customer who has a loooot of data hosts and sources
I started to struggle with the refresh of the site after every "run showrt term tracker" cycle and update on any setting.
Each time TrackMe refreshes and starts at site 1..
Scrolling down to the bottom of the site and skipping about 50 very exhausting, and after some time the short term tracker  
is running again before any configutation could have been done :(

**Describe the solution you'd like**
In case of extraordinary huge lists of hosts/sources (or even metrics) it would be best, if TrackMe remembers the current choosen position of site/page. 

**Describe alternatives you've considered**
It would be also helpful to have the nav bar at the top of the list of hosts/sources (see screenshot attached)

**Additional context**
![TrackMe - Sitenavigation](https://user-images.githubusercontent.com/88150591/127511410-4bd18e88-1ba3-456c-b169-c2ea573d1224.png)

Anyway, this is a nice app!
Thanks.

**Comment by guilhemmarchand** [comment]
Aloha @bl00mberg !

Thanks ;-)

So, first thank for sharing your feedback, much appreciated, and I totally agree and understand, a few things to say / note first:

- You can disable the automatic execution of the refresh (there's a dropdown in the UI to avoid this)

- When doing an update, underneath the app takes the latest values and updates what has to be updated, so even if some of the data is outdated (like the latest data arrival date time, etc) this is not lost

- More important to say, I really advise to use the policy approach for the configuration, that is to focus on creating policies to handle the max lagging essentially, then use tag policies to find entities more easily based on pattenrs (the customer naming convention these kind of things), which in the end allow mass updates more easily.

However, I totally the agree the UI is not ideal on this side, and I dislike the way it refreshes currently.
I take note of the bottom paginator, this might be doable yes.

The real answer is for the future generation of the App which I am working on, will be based on React with splunk-ui and a totally different framework which has nothing to see in term of experience, and so much better on this side of the story.

This work is on-going, it will take some time but soon or late this will be ready ;-)

**Comment by bl00mberg** [comment]
Thanks @guilhemmarchand !
I wasn't noticing the dropdown, sometimes it's the small things..
Your tip with the tag policy saved me probably hours of configuration 👯‍♀️  working in small enviroments I was not paying attetion to this and totally forgot about it. 

Nice! :)

Hope you enjoy the on-going process, I'm glad it's alive and looking foward to new features. 👍
