### ISSUE TITLE
TrackMe bug report - HTML Dashboard deprecated

### ISSUE THREAD

**Issue by jynolen** [guilhemmarchand/trackme#395]
**Describe the bug**
Splunk UI advertise that HTML dashboard is deprecated and dashboard should be rebuild in Dashboard Stduip

**To Reproduce**
1. Go to 'en-US/app/trackme/TrackMe'
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/1485801/167620139-8acf9b30-81ed-4aed-8fea-b4f3bd9f34a7.png)

**Splunk version and deployment:**
TrackMe is deployed on a standalone search head in splunkcloud
![image](https://user-images.githubusercontent.com/1485801/167620469-e2f78162-196b-4ba5-b0eb-c2838fadc4a4.png)

**Comment by jynolen** [comment]
I know it's going to be a pain to migrate, and sadly I don't have much XP with dashboard in order to have a fully 1:1 copy of the behaviors.
I think that migrate to dashboard will need the UI workflow which is really anoying.
I will be pleased to help you for at least migrate the vizualisation of the data.

**Comment by guilhemmarchand** [comment]
Hi @jynolen 

The HTML dashboard deprecation is going to be addressed in the upcoming TrackMe v2, which will be published in a couple of months max. 

"dashboard" is very misleading for an app like TrackMe which performs heavy levels of complex user interractions, TrackMe v2 is a fully rewritten version of the app with much more powerful features.

The Git repo isn't hosted here so you won't see it - but keep on track, it's upcoming ;-)

**Comment by jynolen** [comment]
Hello Guilhelm thanks for clarifications :)
If it's ok for you you (or I) can close the issue since the problem is already addressed with the v2 of the app
