### ISSUE TITLE
Index Time - Last Time / Last Ingest / Last Tiime IDX not updating

### ISSUE THREAD

**Issue by itspaulp** [guilhemmarchand/trackme#78]
On our test devices in a SHC indexing fields last time | last ingest | last time IDX is not updating.  Appears to show only time app first installed.  See screen shot attachment.  Confirmed data is still being indexed and searchable.  What may cause this issue?
![TrackMe_Screenshot](https://user-images.githubusercontent.com/48134418/78412602-c3605200-75c8-11ea-8091-ff3fed2f443e.JPG)

**Comment by guilhemmarchand** [comment]
Hi @itspaulp 

There are no reason why this wouldn't update unless the tracker reports are not enabled or scheduled, or there is an issue in the KVstore synchronisation in your SHC.

TrackMe entirely relies on KVstore based lookups, a first thing you would verify is if running the tracker manually updates the table as expected, you can simply click on the run tracker buttons now, how does it look like ?

You can see the scheduled reports in the app too, and check if there is any complain of the Splunk scheduler, therefore the app will say it too when you will run the tracker within the app.

**Comment by itspaulp** [comment]
Hi Guilhem, 
Thank you for the prompt response! I found my first issue is that we have some orphan searches that been set to admin by default and we had deleted the default admin account. I Created a service account and reassigned all searches from within the app as well so the dates are adjusting now.
So part two of this was kind of weird. Originally all the dates when I first installed had shown as 12/03/2020 and stuck there but then had moved to the 03/04/2020 date that you saw on my first report. now the dates and times are cycling, but they're two months ahead. I thought it might be related to the known date time XML issue, but I've checked my environment and they all seem to be up to date. I am going to go ahead and recheck this one more time.
Thanks,
Paul Perron



Sent from Yahoo Mail on Android 
 
  On Sat, Apr 4, 2020 at 9:44 AM, Guilhem Marchand<notifications@github.com> wrote:   


Hi @itspaulp

There are no reason why this wouldn't update unless the tracker reports are not enabled or scheduled, or there is an issue in the KVstore synchronisation in your SHC.

TrackMe entirely relies on KVstore based lookups, a first thing you would verify is if running the tracker manually updates the table as expected, you can simply click on the run tracker buttons now, how does it look like ?

You can see the scheduled reports in the app too, and check if there is any complain of the Splunk scheduler, therefore the app will say it too when you will run the tracker within the app.

**Comment by guilhemmarchand** [comment]
Closed due to inactivity, please re-open this issue shall this be required.
