### ISSUE TITLE
Wording: "click save", but there is no "save"

### ISSUE THREAD

**Issue by xpac1985** [guilhemmarchand/trackme#96]
When you add an elastic source, and simulate the search successfully, it says "Success, click on save on add this elastic source.", but there is no save button. Not a big deal, but might be confusing.

![2020-06-04_01-34-03_firefox](https://user-images.githubusercontent.com/6882771/83699106-82ee7600-a603-11ea-9232-673e78502ca3.png)

**Comment by guilhemmarchand** [comment]
Thanks a lot @xpac1985 
Will be included in next release.
